// src/config/routes.js
export const ROUTES = {
  HOME: "/",
  HOMEPAGE: "/homepage",
  ELECTRICAL_EQUIPMENT: "/electrical-equipment",
  PRODUCT_DETAIL: "/products/:id",
  ALL_PROJECTS: "/all-projects",
  PROJECT_DETAIL: "/projects/:id",
  CONTACT: "/contact",
  SERVICES: "/services",
  CONSULTANTS: "/services/consultants",
  MAINTENANCE: "/services/maintenance",
  INSPECTIONS: "/services/inspections",
  DISTRIBUTION_GRID: "/industries/distribution-grid",
  CITY_INFRASTRUCTURE: "/industries/city-infrastructure",
  AGRICULTURE: "/industries/agriculture",
  NEWS: "/news",
  NEWS_DETAIL: "/news/:id",
  CAREER: "/career",
  CAREER_DETAIL: "/career/:id",
  NOT_FOUND: "*",
};
