// src/config/routes.js
export const ROUTES = {
  HOME: "/",
  HOMEPAGE: "/homepage",
  ABOUT: "/about",
  ELECTRICAL_EQUIPMENT: "/electrical-equipment",
  SOFTWARE_APPLICATION: "/software-application",
  PRODUCT_DETAIL: (id) => `/products/${id}`,
  ALL_PROJECTS: "/all-projects",
  PROJECT_DETAIL: (id) => `/projects/${id}`,
  CONTACT: "/contact",
  SERVICES: "/services",
  CONSULTANTS: "/services/consultants",
  MAINTENANCE: "/services/maintenance",
  INSPECTIONS: "/services/inspections",
  DISTRIBUTION_GRID: "/industries/distribution-grid",
  CITY_INFRASTRUCTURE: "/industries/city-infrastructure",
  AGRICULTURE: "/industries/agriculture",
  NEWS: "/news",
  NEWS_DETAIL: (id) => `/news/${id}`,
  CAREER: "/career",
  CAREER_DETAIL: (id) => `/career/${id}`,
  NOT_FOUND: "*",
};
